### PR TITLE
Added custom color in pie

### PR DESCRIPTION
**Pull request by YangQi007**
Allow users to set up custom colors for pie chart

### CODE REVIEW

**Comment by anderspitman** [comment]
@YangQi007 I don't quite understand this one. Can't we already set custom colors using the CSS variables `--iobio-data` and `--iobio-data-secondary`?

**Comment by YangQi007** [comment]
> @YangQi007 I don't quite understand this one. Can't we already set custom colors using the CSS variables `--iobio-data` and `--iobio-data-secondary`?

Yes, I saw you set up the --iobio-data and --iobio-data-secondary in the `common.js`, I thought they were default colors for the percent box charts. Can we override it when the mapped reads chart needs another two custom colors?

**Comment by anderspitman** [comment]
@YangQi007 is this PR still valid or superseded by https://github.com/iobio/iobio-charts/pull/118?

**Comment by YangQi007** [comment]
> @YangQi007 is this PR still valid or superseded by [iobio/iobio-charts#118](https://github.com/iobio/iobio-charts/pull/118)?

It is still valid. It is related to https://github.com/iobio/iobio-charts/pull/118. I made changes both in` iobio.viz `and the` iobio-charts` for adding the custom color for the mapped reads chart.

**Review by anderspitman — CHANGES_REQUESTED** [review]
@YangQi007 as mentioned in https://github.com/iobio/iobio-charts/pull/118#pullrequestreview-2419555785, I don't think we need to make changes to iobio.viz.

**Comment by anderspitman** [comment]
Closed per comment above

**Pull request closed without merging**
